# Generated by Django 4.1.7 on 2023-03-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pais',
        ),
    ]
