# Generated by Django 4.1.7 on 2023-03-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pais',
        ),
        migrations.AddField(
            model_name='book',
            name='sexo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], null=True),
        ),
    ]
