# Generated by Django 4.1.7 on 2023-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_book_acompanantes_book_edad_book_numacompanantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='motivos',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Visita Familiares'), (2, 'Vacaciones'), (3, 'Compras'), (4, 'Turismo Cultural'), (5, 'Asistencia Eventos Artisticos'), (6, 'Estudio Formacion'), (7, 'Salud Belleza'), (8, 'Religioso'), (9, 'Congresos Seminarios'), (10, 'Trabajo Remunerado'), (11, 'Trabajo Negocios No Remunerado'), (12, 'Eventos Artisticos Deportivos'), (13, 'Transito'), (14, 'Otro')], null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='organizacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Paquete Colombia'), (2, 'Paquete Pais Visita'), (3, 'Paquete No Agencia Viaje'), (4, 'Cuenta Propia'), (5, 'Otro')], null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='servicios',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Alojamiento'), (2, 'Transporte Internacional'), (3, 'Alimentos Bebidas'), (4, 'Culturales Entretenimiento'), (5, 'Deportivos Recreacionales'), (6, 'Tours Destino'), (7, 'Transporte Aereo En Destino'), (8, 'Otro Transporte'), (9, 'Otro')], null=True),
        ),
    ]
